version: '3'

services:
  api1:
    build:
      context: .
    hostname: api1
    depends_on:
      - db
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '500M'
  
  api2:
    build:
      context: .
    hostname: api2
    depends_on:
      - db
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '500M'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"

    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "500MB"
  
  db:
    image: postgres:15.0-alpine
    hostname: db
    environment:
      PG_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: person_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U root
      interval: 20s
      timeout: 10s
      retries: 5

    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "1000MB"

volumes:
  pg_data:


networks:
  default:
    driver: bridge
    name: rinha